# Generated by Django 3.2.8 on 2021-10-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id_reps', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_de_entidad', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('nivel_de_atencion', models.CharField(max_length=255)),
            ],
        ),
    ]
